version: "3.9"

services: {}
# services:
#   api:
#     image: ghcr.io/acme/api:1.0.0
#     command: ["deno", "task", "start"]
#     environment:
#       NODE_ENV: production
#     deploy:
#       replicas: 2
#     ports:
#       - "8080:80"
#       - target: 9090
#         published: 9090
#         protocol: tcp
#         name: metrics
#     volumes:
#       - "data:/var/lib/data"
#       - source: data
#         target: /var/lib/data
#         read_only: false

volumes: {}
# volumes:
#   data:
#     driver: local
#     driver_opts: {}

networks: {}
configs: {}
secrets: {}
