{{- if .Values.app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctnr-compose.appName" . }}
  labels:
    {{- include "ctnr-compose.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ctnr-compose.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
{{- end }}
