name: ghost
services:
  ghost:
    image: ghost:5-alpine
    ports:
      - '2368:2368'
    environment:
      NODE_ENV: production
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: changeme
      database__connection__database: ghost
      mail__transport: SMTP
    depends_on:
      - db
    volumes:
      - ghost-data:/var/lib/ghost/content
    restart: always
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: changeme
    volumes:
      - ghost-db-data:/var/lib/mysql
    restart: always
volumes:
  ghost-data: {}
  ghost-db-data: {}
