---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ctnr-env
  namespace: ctnr-system
data:
  DEBUG: "${DEBUG}"
  LOG_LEVEL: "${LOG_LEVEL}"

  CTNR_API_URL: "${CTNR_API_URL}"
  CTNR_APP_URL: "${CTNR_APP_URL}"
  CTNR_VERSION: "${CTNR_VERSION}"

  SUPABASE_URL: "${SUPABASE_URL}"
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}"

  GITHUB_APP_CLIENT_ID: "${GITHUB_APP_CLIENT_ID}"
  GITHUB_APP_CLIENT_SECRET: "${GITHUB_APP_CLIENT_SECRET}"

  MOLLIE_MODE: "${MOLLIE_MODE}"
  MOLLIE_API_URL: "${MOLLIE_API_URL}"
  MOLLIE_API_KEY: "${MOLLIE_API_KEY}"
  MOLLIE_PROFILE_ID: "${MOLLIE_PROFILE_ID}"
  
  QONTO_API_URL: "${QONTO_API_URL}"
  QONTO_API_LOGIN: "${QONTO_API_LOGIN}"
  QONTO_API_SECRET_KEY: "${QONTO_API_SECRET_KEY}"
  QONTO_IBAN: "${QONTO_IBAN}"

  KUBECONFIG: "${KUBECONFIG}"
